## sql-server express

services:
  sql_server:
    container_name: "sql_server"
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'sqlserver@2019'
      MSSQL_PID: 'Express'
    ports:
      - 1433:1433
    volumes: # sudo chmod -R 775 ./data/
      - "./sqlserver/data:/var/opt/mssql/data"
      - "./sqlserver/log:/var/opt/mssql/log"
      - "./sqlserver/secrets:/var/opt/mssql/secrets"
    restart: "always"   

