services:
  mysql_server:
    image: 'mysql:8.0'
    container_name: 'mysql_server'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    restart: 
      always
    ports:
      - 3306:3306
